// Command server runs the Mailat API. The OpenAPI contract is generated by
// cmd/openapi and served at /api/v1/openapi.json; /docs/ renders it.
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/gogf/gf/v2/frame/g"

	"github.com/dublyo/mailat/api/internal/config"
	"github.com/dublyo/mailat/api/internal/controller"
	"github.com/dublyo/mailat/api/internal/database"
	"github.com/dublyo/mailat/api/internal/eventoutbox"
	"github.com/dublyo/mailat/api/internal/router"
	"github.com/dublyo/mailat/api/internal/service"
	"github.com/dublyo/mailat/api/internal/worker"
)

func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		fmt.Printf("Failed to load config: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Starting Mailat API server %s...\n", controller.BuildVersion)
	fmt.Printf("Environment: %s\n", cfg.Env)

	// Connect to PostgreSQL
	db, err := database.Connect(cfg)
	if err != nil {
		fmt.Printf("Failed to connect to PostgreSQL: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()
	fmt.Println("Connected to PostgreSQL")
	if cfg.AutoMigrate {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		err := database.Migrate(ctx, db)
		cancel()
		if err != nil {
			fmt.Printf("Database migration failed: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("Database schema is up to date")
	}

	// Redis is required: startup exits without it and /health reports it.
	// WORKER_ENABLED only controls the Asynq worker and scheduler below.
	redis, err := database.ConnectRedis(cfg)
	if err != nil {
		fmt.Printf("Failed to connect to Redis: %v\n", err)
		os.Exit(1)
	}
	defer redis.Close()
	fmt.Println("Connected to Redis")

	// Database-backed recovery loops run in every API process, even with
	// WORKER_ENABLED=false. Each loop has one owner per process and shares shutdown.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	var recovery sync.WaitGroup
	recovery.Add(7)
	go func() { defer recovery.Done(); eventoutbox.Run(ctx, db) }()
	go func() { defer recovery.Done(); service.RunDMARCReportBackfill(ctx, db, cfg) }()
	go func() { defer recovery.Done(); worker.NewEmailHandler(db, cfg).RunPending(ctx) }()
	go func() { defer recovery.Done(); service.RunCampaignSender(ctx, db, cfg) }()
	// Email steps queue rows in the step transaction; the mailer sends them after commit.
	go func() {
		defer recovery.Done()
		service.RunAutomationExecutor(ctx, db, cfg, service.NewAutomationMailer(db, cfg))
	}()
	go func() { defer recovery.Done(); service.RunAutomationMailer(ctx, db, cfg) }()
	// Auto-replies, forwards and push run from jobs queued in the SES ingest transaction.
	go func() {
		defer recovery.Done()
		runner := service.NewArrivalRunner(db, cfg, service.NewTransactionalService(db, cfg, redis))
		if push := service.NewPushNotificationService(db, cfg); push.Enabled() {
			runner.SetPusher(push)
		}
		runner.Run(ctx)
	}()

	// Start worker if enabled
	var w *worker.Worker
	var sched *worker.Scheduler
	if cfg.WorkerEnabled {
		w = worker.NewWorker(db, cfg)
		w.SetDigestSender(service.NewTransactionalService(db, cfg, redis).AlertDigestSender())
		go func() {
			if err := w.Start(); err != nil {
				fmt.Printf("Worker failed: %v\n", err)
			}
		}()
		fmt.Println("Worker started (asynq job queue)")

		// Start scheduler for periodic tasks
		sched, err = worker.NewScheduler(db, cfg)
		if err != nil {
			fmt.Printf("Warning: failed to create scheduler: %v\n", err)
		} else {
			if err := sched.RegisterScheduledTasks(); err != nil {
				fmt.Printf("Warning: failed to register scheduled tasks: %v\n", err)
			} else {
				go func() {
					if err := sched.Start(); err != nil {
						fmt.Printf("Scheduler failed: %v\n", err)
					}
				}()
				fmt.Println("Scheduler started (periodic tasks)")
			}
		}
	}

	// Start delivery tracker (PostgreSQL NOTIFY listener)
	var tracker *service.DeliveryTracker
	tracker, err = service.NewDeliveryTracker(db, cfg)
	if err != nil {
		fmt.Printf("Warning: failed to create delivery tracker: %v\n", err)
	} else {
		if err := tracker.Start(ctx); err != nil {
			fmt.Printf("Warning: failed to start delivery tracker: %v\n", err)
		} else {
			fmt.Println("Delivery tracker started (PostgreSQL NOTIFY)")
		}
	}

	// Create GoFrame server
	s := g.Server()
	s.SetPort(cfg.Port)
	s.SetDumpRouterMap(false)

	// Setup routes
	router.SetupWithContext(ctx, s, cfg)

	// Graceful shutdown

	go func() {
		<-ctx.Done()
		fmt.Println("\nShutting down server...")
		if tracker != nil {
			tracker.Stop()
		}
		if sched != nil {
			sched.Shutdown()
		}
		if w != nil {
			w.Shutdown()
		}
		s.Shutdown()
	}()

	// Start server
	fmt.Print(startupBanner(cfg.Port, controller.BuildVersion))

	s.Run()
	stop()
	recovery.Wait()
}

// startupBanner names the build and the two documentation surfaces the API
// itself serves. Route lists belong in the OpenAPI contract, not here.
func startupBanner(port int, version string) string {
	return fmt.Sprintf("\nMailat API %s\n  Docs:    http://localhost:%d/docs/\n  OpenAPI: http://localhost:%d/api/v1/openapi.json\n\n", version, port, port)
}
